### ISSUE TITLE
Headers set by fastify are ignored if `express` handles request

### ISSUE THREAD

**Issue by SimenB** [fastify/fastify-express#13]
## 🐛 Bug Report

If I set headers via some hook in fastify, they are not included in the response if an express handler handles the request.

This is not true the other way around - if an express middleware sets a header it's included in the response no matter of it's express or fastify the responds.

## To Reproduce

```js
const fastify = require('fastify')();
const fastifyExpress = require('fastify-express');
const fp = require('fastify-plugin');
const express = require('express');

fastify.register(
  fp(
    (instance, _, next) => {
      instance.addHook('preValidation', (_, reply, done) => {
        reply.headers({
          foo: 'bar',
        });

        done();
      });

      next();
    },
    { fastify: '3.x' },
  ),
);

fastify.register(fastifyExpress).after(() => {
  const router = express.Router();

  router.use('/express', (_, res) => {
    res.sendStatus(200);
  });

  fastify.use(router);
});

fastify.get('/fastify', (_, reply) => {
  reply.code(200).send();
});

fastify.listen(3000);
```

```sh-session
$ curl -i http://localhost:3000/fastify 
HTTP/1.1 200 OK
foo: bar
content-length: 0
Date: Thu, 22 Oct 2020 10:48:01 GMT
Connection: keep-alive
Keep-Alive: timeout=5

$ curl -i http://localhost:3000/express
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 2
ETag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
Date: Thu, 22 Oct 2020 10:48:03 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

FWIW, using `reply.raw.setHeader` doesn't work either.

## Expected behavior

I would expect the header to be written to the response regardless of express handling the request or not.

This makes it impossible to migrate parts of our app piecemeal to Fastify as the headers set (specifically HSTS headers now) are ignored.

## Your Environment

- *node version*: v12.19.0
- *fastify version*: 3.7.0
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
You need to implement this same thing here: https://github.com/fastify/fastify-nextjs/pull/112.

Fastify does not use `setHeader()` because it's _expensive_ to do so (we use `writeHead` instead).

**Comment by SimenB** [comment]
I tried `reply.raw.setHeader` in my hook without success - my test might have been faulty, tho

**Comment by mcollina** [comment]
if `reply.raw.setHeader` does not work... it means `express` is overriding `setHeader` in its prototype implementation... this will be tricky to solve.

**Comment by SimenB** [comment]
My bad, I used `addHook('preValidation'` instead of `addHook('onRequest'` - using correct hook makes `setHeader` work! PR: #14.

I guess we'll have to ensure we're careful where we set headers until we can remove express entirely
