### ISSUE TITLE
Express routes don't work when an Express router is added inside a plugin

### ISSUE THREAD

**Issue by simonplend** [fastify/fastify-express#26]
## 🐛 Bug Report

This is probably less of a bug and more of a potential opportunity to improve the documentation for this plugin. I would like to clarify a couple of things before I open a pull request.

The [README](README.md) for this plugin provides an example of how you can [add a complete application](https://github.com/fastify/fastify-express#add-a-complete-application) (an Express router instance in the example). If I follow this example and `use()` an Express router instance at the root context of a Fastify server the Express routes work as expected. If I `use()` the Express router instance inside a plugin, the routes do not work.

This was surprising as the [encapsulation support](https://github.com/fastify/fastify-express#encapsulation-support) example implies that all Express code can be registered inside a plugin, although it doesn't explicitly include Express routes.

This issue has been [discussed](https://discord.com/channels/725613461949906985/725613462373269567/818866916868620289) on the Fastify Discord. @etino has demonstrated that it is possible to call `use()` with an Express router instance inside of a plugin and have the routes work if you wrap the plugin with [fastify-plugin](https://github.com/fastify/fastify-plugin). This hints at this issue being related to scope.

In conclusion, this *might* be a bug, but my understanding of scoping in Fastify is not complete enough to determine if this is expected behaviour. If it is expected behaviour, I propose updating the README in one of two ways:

1. Document that if you want to add Express routes inside of a plugin that you will need to wrap that plugin with `fastify-plugin` (unless that is not advisable for reasons I'm unaware of).
2. Document that Express routes must be added by calling `use()` on the root context of a Fastify server.

Sidenote: I've noticed a test for [registering a complete Express application](https://github.com/fastify/fastify-express/blob/master/test/application.test.js#L10-L41) i.e. an Express server instance, as opposed to an Express router instance. Should this be documented in the README?

## To Reproduce

```js
import express from "express";
import Fastify from "fastify";
import FastifyExpress from "fastify-express";

const fastify = Fastify({
	logger: true,
});

fastify.register(async function routes(fastify) {

	// 200 OK
	fastify.get("/fastify", (request, reply) => {
		reply.send({ hello: "fastify" })
	});

	await fastify.register(FastifyExpress);

	const router = express.Router();

	// Error: 404 Not Found
	router.get("/express", (request, response) => {
		response.json({ hello: "express" });
	});

	fastify.use(router);
});

try {
	await fastify.listen(3000);
} catch (error) {
	fastify.log.error(error);
	process.exit(1);
}
```

## Expected behavior

Express routes work regardless of the scope at which they are added with the `use()` method that this plugin exposes. If this is not desirable, then the documentation should reflect that.

## Your Environment

- *node version*: 14.16.0
- *fastify version*: 3.13.0
- *os*: Linux

**Comment by mcollina** [comment]
Go ahead and make the README changes, they are necessary.

The reason why it's required for this to be global is that it is executed in the `onRequest` lifecycle of the "not found" handler. 
Given how Fastify routing works, it's going to be really hard to overcome this limitation.

We could potentially support (which currently isn't):

```js
import express from "express";
import Fastify from "fastify";
import FastifyExpress from "fastify-express";

const fastify = Fastify({
	logger: true,
});

fastify.register(async function routes(fastify) {

	fastify.get("/fastify", (request, reply) => {
		reply.send({ hello: "fastify" })
	});

	await fastify.register(FastifyExpress);

	const router = express.Router();

	router.get("/express", (request, response) => {
		response.json({ hello: "express" });
	});

	fastify.use(router);
        fastify.setNotFound(async function () { return 'not found' }) // needed 
}, { prefix: '/a' ); // prefix needed

try {
	await fastify.listen(3000);
} catch (error) {
	fastify.log.error(error);
	process.exit(1);
}
```

**Comment by simonplend** [comment]
@etino Thanks for adding this context.

> But I don't know if this approach maintains the encapsulation requirement.

What do you mean by "the encapsulation requirement"?

**Comment by simonplend** [comment]
@mcollina 

> The reason why it's required for this to be global is that it is executed in the `onRequest` lifecycle of the "not found" handler.
> Given how Fastify routing works, it's going to be really hard to overcome this limitation.

This is really useful to know.

> We could potentially support (which currently isn't) with minimal code changes:
> ...
> However I'm thinking it would just complicate the life of our users.

Agreed. Given the purpose of this package - to support an application's transition phase from Express to Fastify - it seems unnecessary to support lots of different use cases. If the supported use cases _and_ limitations of this plugin are clearly documented, that should be enough.

**Comment by simonplend** [comment]
I started work on changes to the README, however as I was doing this I noticed the example code for [Restrict middleware execution to a certain path(s)](https://github.com/fastify/fastify-express#restrict-middleware-execution-to-a-certain-paths).

This example code demonstrates adding the `serve-static` Express middleware with _specific paths_ inside a plugin. As we've identified that you need to add middleware which depends on routing to Fastify's root context, I was curious how this code could work. Having tested it out, it doesn't look like it does unfortunately.

I've created a minimal reproduction: https://github.com/simonplend/fastify-express/tree/examples-testing/examples-testing/restrict-middleware-certain-paths

**Comment by mcollina** [comment]
FYI, the example uses `cors`, which will be applied to all fastify routes in that plugin - it is a pass-through middleware. `serve-static` adds new routes and it won't work.

**Comment by etino** [comment]
> @etino Thanks for adding this context.
> What do you mean by "the encapsulation requirement"?

I was referring to the [Encapsulation](https://www.fastify.io/docs/latest/Encapsulation/), supposing that a route should always be declared in the root context.

This is the reason I suggested the `fastify-plugin` approach.

But looking at the example in the Encapsulation documentation page, I see that all routes are available even if declared in the child or grandchild plugins. I was misled by the [Plugin - Handle the scope](https://www.fastify.io/docs/master/Plugins/#handle-the-scope) page thinking that all routes need to be declared in the root scope or declared using `fastify-plugin` to be available.

**Comment by simonplend** [comment]
> FYI, the example uses `cors`, which will be applied to all fastify routes in that plugin - it is a pass-through middleware. `serve-static` adds new routes and it won't work.

Thanks for the extra details. Is this in response to [my comment](https://github.com/fastify/fastify-express/issues/26#issuecomment-800133458) about the README example which uses `serve-static`?

If so, I'm happy to address that in my README changes as well, but I just want to clarify: is it accurate to say that you can use this plugin to add_any_ middleware (with or without paths) to the root context of a Fastify server, but you can only add middleware inside a plugin which doesn't require paths?

**Comment by mcollina** [comment]
Middleware support is built on top of Fastify hooks and encapsulation. I recommend reading https://github.com/fastify/fastify/blob/master/docs/Encapsulation.md, https://github.com/fastify/fastify/blob/master/docs/Hooks.md and all the docs about plugins.

Trying to extrapolate a complex (and powerful) behavior in a sentence will lead to incorrect assumptions. Simplifying a bit, middleware registered with use `.use()` will be applied wherever a `onRequest` hook is applied: a route matches the request URL or it exists a not found handler for the given prefix. Therefore, if the wanted behavior is to route through express all the requests that are not matched by fastify own router, this behavior __must__ be registered at the top of level so that it is installed for all descending routes and not found handlers.

---

> Thanks for the extra details. Is this in response to my comment about the README example which uses serve-static?

Yes.

**Comment by simonplend** [comment]
Ok, I'll give the Encapsulation and Hooks documentation a re-read to to consolidate my understanding of how this plugin is working.

> Trying to extrapolate a complex (and powerful) behavior in a sentence will lead to incorrect assumptions.

That's a fair point. I'll correct and update this README with clearer instructions around the plugin's usage and limitations. I'll try and accurately reflect what you've described about the underlying implementation.
