### ISSUE TITLE
FST_ERR_DEC_ALREADY_PRESENT when register fastify-express

### ISSUE THREAD

**Issue by leviscar** [fastify/fastify-express#36]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.14.0

### Plugin version

0.3.2

### Node.js version

12.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.13.6

### Description

FST_ERR_DEC_ALREADY_PRESENT when register fastify-express

![image](https://user-images.githubusercontent.com/18376002/120679204-7f6a2500-c4cb-11eb-89f9-586739241e0d.png)

### Steps to Reproduce

```
const fastify = require('fastify');
const cors = require('cors');

async function build() {
    const fastifyInstance = fastify();
    await fastifyInstance.register(require('fastify-express'));
    fastifyInstance.use(cors());
    return fastifyInstance;
};

build().then(fastify => fastify.listen(3000, (err, port) => {
    console.warn(`server listening on ${port}`);
    if (err) {
        process.exit(1);
    };
})).catch(console.log);
```

**Comment by jsumners** [comment]
I copied and pasted your reproduction and do not see the issue:

![image](https://user-images.githubusercontent.com/321201/120679878-aa229200-c467-11eb-9c30-bda0fd7d8514.png)

**Comment by leviscar** [comment]
sorry, I check the version of my fastify ，it's 2.14.0，that's the problem.  I will close the issue
