### ISSUE TITLE
Headers are `null` when using `.inject`

### ISSUE THREAD

**Issue by SimenB** [fastify/fastify-express#47]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.2

### Plugin version

0.3.3

### Node.js version

14.17.5

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.5.1

### Description

When using `fastify.inject` and this plugin, `res.headers` is always `null`. The headers are in `res.raw.res.getHeaders()` FWIW.

Debugging, https://github.com/fastify/light-my-request/blob/014c1c8016f8605b5ca4c7906f527d5ab0b17267/lib/response.js#L66-L81 is never called

### Steps to Reproduce

In this repo, change `fastify.listen` to `fastify.inject`

```diff
diff --git i/test/application.test.js w/test/application.test.js
index a8e1915..a28e4dd 100644
--- i/test/application.test.js
+++ w/test/application.test.js
@@ -166,14 +166,11 @@ test('Should flush headers if express handles request', t => {
     .register(expressPlugin)
     .after(() => { fastify.use(router) })
 
-  fastify.listen(0, (err, address) => {
+  fastify.inject({
+    method: 'GET',
+    url: '/'
+  }, (err, res) => {
     t.error(err)
-    sget({
-      method: 'GET',
-      url: address
-    }, (err, res) => {
-      t.error(err)
-      t.strictEqual(res.headers.foo, 'bar')
-    })
+    t.strictEqual(res.headers.foo, 'bar')
   })
 })
```

![image](https://user-images.githubusercontent.com/1404810/129695542-e41c96aa-b6b0-4fab-b8ae-8fd870a8b0ef.png)

### Expected Behavior

`headers` should be populated

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by SimenB** [comment]
Happy to, but I don't know what the fix is. Any pointers?

**Comment by mcollina** [comment]
The fix should be here.

**Comment by SimenB** [comment]
Right, makes sense. I don't think I'll be able to send a PR though as I don't know what the fix is 😅

**Comment by mcollina** [comment]
My understanding is that light-my-request cannot work with Express as the latter does a lot of prototype chain manipulation that light-my-request is not really liking.

I think the fix should/would be in light-my-request.

**Comment by SimenB** [comment]
Yeah, that seems reasonable. I can send the PR I was talking about above, and we can figure out if it's an ok way to go?

**Comment by mcollina** [comment]
let's see!

**Comment by SimenB** [comment]
Opened up fastify/light-my-request#154

**Comment by SimenB** [comment]
This has regressed as of https://github.com/fastify/light-my-request/pull/221

apply this diff to get a failure (same as OP, but that doesn't apply cleanly anymore):

```diff
diff --git i/test/application.test.js w/test/application.test.js
index efc0e4c..a8a44c3 100644
--- i/test/application.test.js
+++ w/test/application.test.js
@@ -145,7 +145,7 @@ test('Should expose the express app on the fastify instance', t => {
 })
 
 test('Should flush headers if express handles request', t => {
-  t.plan(3)
+  t.plan(2)
   const fastify = Fastify()
   t.teardown(fastify.close)
 
@@ -166,14 +166,11 @@ test('Should flush headers if express handles request', t => {
     .register(expressPlugin)
     .after(() => { fastify.use(router) })
 
-  fastify.listen({ port: 0 }, (err, address) => {
+  fastify.inject({
+    method: 'GET',
+    url: '/'
+  }, (err, res) => {
     t.error(err)
-    sget({
-      method: 'GET',
-      url: address
-    }, (err, res) => {
-      t.error(err)
-      t.equal(res.headers.foo, 'bar')
-    })
+    t.equal(res.headers.foo, 'bar')
   })
 })
```

**Comment by Eomm** [comment]
I found the issue: the writehead method is not called because of this line in fastify:

```
Reply.prototype.status = Reply.prototype.code
```

I think the best solution would be to that light-my-request support both the cases instead that this module care about the fastify internals

**Comment by Eomm** [comment]
Ok, after a lot of debugging, I found that the `reply.raw.end` function is overwritten during the code flow.


If you log `reply.raw.end.toString()`, you will see that it changes from:

- `fastify-express/index.js`
- `router.get('/', (req, res) => { console.log(res.end.toString())`

The issue comes from here:

https://github.com/expressjs/express/blob/33e8dc303af9277f8a7e4f46abfdcb5e72f6797b/lib/application.js#L237-L239

This code is executed after three express `layer`s:

- `function query(req, res, next)`
- `function expressInit(req, res, next)` * that changes the proto
- finally the router `function router(req, res, next)` that receives the wrong object

This prototype switching simply does not execute the `light-my-request` code.

So, now I think that we should find how to configure/fix this project instead or, restoring the previous code in `lmr` that copies the headers.
In the latter case, I was unable to replicate this issue/configuration on that repository 😞 

What I tried but failed to do on this repo:

```
Object.assign(fastify.express.response, LmrResponse)

Object.setPrototypeOf(Object.getPrototypeOf(reply.raw), LmrRequest.prototype)
```

**Comment by SimenB** [comment]
@mcollina should we reintroduce the header code removed from `light-my-request` up until a cleaner solution is available? Even though we seem unable to reproduce it properly outside of `fastify-express`.

**Comment by mcollina** [comment]
I have no time to dig into the problem atm (I'll be very busy until mid-october), I'm ok with a full revert or whatever fix you think it's appropriate.

**Comment by SimenB** [comment]
Cool, I'll send a PR 👍 

I don't think we need to revert, just re-add the somewhat hacky header code
