### ISSUE TITLE
Unable to get plugin working with typescript + require

### ISSUE THREAD

**Issue by guillenotfound** [fastify/fastify-express#69]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

If I use `require` to import the plugin that won't play well with Typescript and will raise the following error:

```
TSError: ⨯ Unable to compile TypeScript:
src/node/loaders/vite.ts:21:7 - error TS2339: Property 'use' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'.

21   app.use(viteServer.middlewares)
```

Instead if I import the plugin using import it works well, but I don't need the plugin on production, just on development, so is there any way to get it working using require instead of import?

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by guillenotfound** [comment]
BTW found the solution on my own, here is an updated version of the readme just in case it help others: https://github.com/fastify/fastify-express/pull/70
